<?php

function clinica_node_insert($node){
  if ($node->type == "pet"){
    $updateNode = node_load($node->nid);
    $updateNode->title = $node->title . ' - ' . $node->name;
    node_save($updateNode);
  }
}

function clinica_user_login(&$edit, $account) {
  drupal_goto('user-page');
}

/**
 * Implementation of hook_menu().
 */
function clinica_menu() {

  $menuitems['report-pet'] = array(
    'title' => 'Pets',
    'page callback' => '_pets_list',
    'access callback' => 'user_is_logged_in',
    'menu_name' => 'main-menu',
    'type' => MENU_NORMAL_ITEM,
  );

  $menuitems['schedules'] = array(
    'title' => 'Agendametos',
    'page callback' => '_my_scheduler_list',
    'access callback' => 'user_is_logged_in',
    'menu_name' => 'main-menu',
    'type' => MENU_NORMAL_ITEM,
  );

  $menuitems['sobre-nos'] = array(
    'title' => 'Quem Somos',
    'page callback' => 'clinica_mymenu_page_callback',
    'access callback' => 'user_is_anonymous',
    'menu_name' => 'main-menu',
    'type' => MENU_NORMAL_ITEM,
  );

  $menuitems['Serviços'] = array(
    'title' => 'Serviços',
    'page callback' => 'clinica_mymenu_page_callback',
    'access callback' => 'user_is_anonymous',
    'menu_name' => 'main-menu',
    'type' => MENU_NORMAL_ITEM,
  );

  $menuitems['login'] = array(
    'title' => 'Entrar',
    'page callback' => '_login_page',
    'access callback' => 'user_is_anonymous',
    'menu_name' => 'main-menu',
    'type' => MENU_NORMAL_ITEM,
  );

  return $menuitems;

}

function avanz_relatorios_theme()
{
  return array(
    'clinica_pets_reports' => array(
      'template' => 'templates/relatorio.pets',
      'variables' => array('dados' => NULL),
    )
  );
}

/**
 * @return string
 */
function _login_page() {
  $result = "<a href='/user'>Login</a> <br>";
  $result.="<a href='/user/register'>Registrar-se</a>";
  return $result;
}

function _pets_list() {
  return views_embed_view('pet_s', 'page');
}

function _my_scheduler_list() {
  global $user;
  if (in_array('Tutor', $user->roles)){
    return views_embed_view('agendamentos', 'page');
  }

  return views_embed_view('agendamentos', 'page_1');
}







