<?php

/**

 * Implementation of hook_menu().

 */

function clinica_menu() {

  $menuitems['schedules'] = array(
    'title' => 'Agendametos',
    'page callback' => 'clinica_reports',
    'access callback' => 'user_is_logged_in',
    'menu_name' => 'main-menu',
    'type' => MENU_NORMAL_ITEM,
  );

  $menuitems['create/pet'] = array(
    'title' => 'Adicionar pet',
    'page callback' => 'clinica_reports',
    'access callback' => 'user_is_logged_in',
    'menu_name' => 'main-menu',
    'type' => MENU_NORMAL_ITEM,
  );

  $menuitems['reports'] = array(
    'title' => 'Relatorios',
    'page callback' => 'clinica_reports',
    'access callback' => 'user_is_logged_in',
    'menu_name' => 'main-menu',
    'type' => MENU_NORMAL_ITEM,
  );

  $menuitems['sobre-nos'] = array(
    'title' => 'Quem Somos',
    'page callback' => 'clinica_mymenu_page_callback',
    'access callback' => 'user_is_anonymous',
    'menu_name' => 'main-menu',
    'type' => MENU_NORMAL_ITEM,
  );

  $menuitems['Serviços'] = array(
    'title' => 'Serviços',
    'page callback' => 'clinica_mymenu_page_callback',
    'access callback' => 'user_is_anonymous',
    'menu_name' => 'main-menu',
    'type' => MENU_NORMAL_ITEM,
  );

  $menuitems['login'] = array(
    'title' => 'Entrar',
    'page callback' => 'clinica_mymenu_page_callback',
    'access callback' => 'user_is_anonymous',
    'menu_name' => 'main-menu',
    'type' => MENU_NORMAL_ITEM,
  );

  return $menuitems;

}

function clinica_mymenu_page_callback() {
  $result = "<a href='/user'>Login</a> <br>";
  $result.="<a href='/user/register'>Registrar-se</a>";
  return $result;
}

function clinica_reports() {

}
