<?php

//
//function clinica_scheduler_form_node_form_alter(&$form, &$form_state, $form_id) {
//  if ($form_id == 'scheduler_node_form'){
//    $daySelected = $form['field_day']['und']['value'];
//    $availableHours = $form["field_horario"]['und']['#options'];
//    dpm($form['field_day']); die;
//    $date = new DateTime($daySelected);
//    echo $date->getTimestamp();
//    unset($availableHours[8]);
//
//   // var_dump($availableHours); die;
//  }
//}
//
//function searchHoursScheduler() {
//global $user;
//
//$query = db_select('node', 'n');
//$query->fields('n');
//$query->condition('type', 'scheduler');
//$query->condition('uid', $user->uid);
//$query->leftJoin('field_data_field_day', 'day', 'day.entity_id = n.nid');
//$query->addExpression('day.field_day_value', 'date');
//$rs = $query->execute()->fetchAll();
//print_r($rs);
//}
